### PR TITLE
Use new public sandbox root URL

### PR DESCRIPTION
**Pull request by MaxPhilips**

### CODE REVIEW

**Review by amcginn — APPROVED** [review]

**Comment by kolkheang** [comment]
@MaxPhilips 

Are these values still correct for this new environment?

```
<label for='practitioner' class='col-sm-2 col-form-label'>Practitioner</label>
              <div class='col-sm-10'>
                <select class='form-control' id='practitioner' name='schedule.actor' required>
                  <option value='Practitioner/1672007'>Andrew Robertson</option>
                  <option value='Practitioner/1418008'>Phil V Brewer</option>
                  <option value='Practitioner/937933'>Bryce Barney Burns</option>
                  <option value='Practitioner/937934'>Christine Carly Chambers</option>
                  <option value='Practitioner/605926'>Kristen Cerner Carter</option>
                </select>
              </div>
            </div>

            <div class='form-group row'>
              <label for='location' class='col-sm-2 col-form-label'>Location</label>
              <div class='col-sm-10'>
                <select class='form-control' id='location' name='-location' required>
                  <option value='4048128'>Baseline East Medical Center</option>
                  <option value='4048296'>Family Practice Clinic</option>
                </select>
              </div>
            </div>
```

**Comment by amcginn** [comment]
> @MaxPhilips
> 
> Are these values still correct for this new environment?
> 
> ```
> <label for='practitioner' class='col-sm-2 col-form-label'>Practitioner</label>
>               <div class='col-sm-10'>
>                 <select class='form-control' id='practitioner' name='schedule.actor' required>
>                   <option value='Practitioner/1672007'>Andrew Robertson</option>
>                   <option value='Practitioner/1418008'>Phil V Brewer</option>
>                   <option value='Practitioner/937933'>Bryce Barney Burns</option>
>                   <option value='Practitioner/937934'>Christine Carly Chambers</option>
>                   <option value='Practitioner/605926'>Kristen Cerner Carter</option>
>                 </select>
>               </div>
>             </div>
> 
>             <div class='form-group row'>
>               <label for='location' class='col-sm-2 col-form-label'>Location</label>
>               <div class='col-sm-10'>
>                 <select class='form-control' id='location' name='-location' required>
>                   <option value='4048128'>Baseline East Medical Center</option>
>                   <option value='4048296'>Family Practice Clinic</option>
>                 </select>
>               </div>
>             </div>
> ```

ah, nope. these should be updated as well.

**Comment by MaxPhilips** [comment]
the practitioner ids will need more work than URL updates and I plan to work on them separately

**Comment by MaxPhilips** [comment]
we'll get practitioners, locations, and proprietary codes updated within this PR

**Review by BroadwayBean — APPROVED** [review]

**Review by amcginn — APPROVED** [review]

**Comment by MaxPhilips** [comment]
noticed a few other changes and applied them here: https://github.com/cerner/smart-on-fhir-scheduling-tutorial/commit/f446c858f5f1dc6340a0172f2cc7f8c3d26396de

**Pull request merged**
